// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDuFU_pFb1u5GsIFAk_lmBZolkrVyyE34',
    appId: '1:427680799387:web:2968e967c905c402c6443e',
    messagingSenderId: '427680799387',
    projectId: 'mathquiz-51f92',
    authDomain: 'mathquiz-51f92.firebaseapp.com',
    storageBucket: 'mathquiz-51f92.firebasestorage.app',
    measurementId: 'G-PKMKEY7WHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfozO8xlrW16x3wt9Xto_DmaHsDyQhds',
    appId: '1:427680799387:android:1b575c851cfed5c9c6443e',
    messagingSenderId: '427680799387',
    projectId: 'mathquiz-51f92',
    storageBucket: 'mathquiz-51f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6rTZhxnGWpfJsxyGI8v3TfTd1_3SGYqI',
    appId: '1:427680799387:ios:d18cb634e4453e8fc6443e',
    messagingSenderId: '427680799387',
    projectId: 'mathquiz-51f92',
    storageBucket: 'mathquiz-51f92.firebasestorage.app',
    iosBundleId: 'com.example.mathquiz',
  );

}